name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: 0 0 * * *

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: felipecrs
      IMAGE_NAME: devcontainer
    steps:
      - uses: actions/checkout@v4
      - name: Docker meta (base)
        id: docker-meta-base
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
          tags: |
            type=schedule,pattern=nightly
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=ref,event=branch
            type=ref,event=pr
            type=sha,enable=${{ github.event_name == 'push' }}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) || github.event_name == 'schedule' }}
            type=raw,value=base,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) || github.event_name == 'schedule' }}
          bake-target: base
      - name: Docker meta (github)
        id: docker-meta-github
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
            prefix=github-
          tags: |
            type=schedule,pattern=nightly
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=ref,event=branch
            # Prefix needs to be repeated for these, refs:
            # https://github.com/docker/metadata-action/issues/270
            type=ref,event=pr,prefix=github-pr-
            type=sha,prefix=github-sha-,enable=${{ github.event_name == 'push' }}
          bake-target: github
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/bake-action@v4
        with:
          pull: true
          no-cache: true
          push: ${{ github.event_name != 'pull_request' }}
          files: |
            ./docker-bake.hcl
            ${{ steps.docker-meta-base.outputs.bake-file }}
            ${{ steps.docker-meta-github.outputs.bake-file }}
      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.DOCKERHUB_USERNAME }}/devcontainer
