name: ci

on:
  - push

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PASSWORD }}
      - name: devcontainer:base - build and push
        uses: docker/build-push-action@v2
        with:
          context: ./images/devcontainer
          target: base
          push: true
          tags: |
            felipecrs/devcontainer:base
            felipecrs/devcontainer:latest
            ghcr.io/felipecrs/devcontainer:base
            ghcr.io/felipecrs/devcontainer:base
      - name: devcontainer:python - build and push
        uses: docker/build-push-action@v2
        with:
          context: ./images/devcontainer
          target: python
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            felipecrs/devcontainer:python
            felipecrs/devcontainer:python3
            ghcr.io/felipecrs/devcontainer:python
            ghcr.io/felipecrs/devcontainer:python3
      - name: devcontainer - update Docker Hub description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: felipecrs/devcontainer
          readme-filepath: ./images/devcontainer/README.md